### ISSUE TITLE
Adding a ttl to a rabbit queue gives a PRECONDITON FAILED error

### ISSUE THREAD

**Issue by timyates** [pmlopes/mod-stomp-io#7]
If I create a rabbitmq queue with a ttl setting, ie pass

```
message-ttl : 10000
```

On queue creation, then when I try to subscribe to the queue, I get the error:

> PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'demo_live_vertx_queue' in vhost '/': received none but current is the value '10000' of type 'long'

Unsure if this is an issue my end, or something that needs looking at in the stomp integration... but thought I'd put it here for the time being...

Investigating, but any hints would be appreciated :smiley:

**Comment by yisuoyanyu111** [comment]
need to choose the special vhost,because some rabbitmq account only has some special vhosts permission。example:
![image](https://user-images.githubusercontent.com/5451176/63822746-eddb9400-c983-11e9-90e2-1e9aebee0976.png)
